### ISSUE TITLE
how to donload notes of dsa? I'm not able to find notes option

### ISSUE THREAD

**Issue by sourabh00011** [kunal-kushwaha/DSA-Bootcamp-Java#1003]
how to donload notes of dsa? I'm not able to find notes option. please tell me step by step anybody

**Comment by Pyth0nHere** [comment]
**Assignments** :point_down:
[https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/assignments](url)

**Lectures** :point_down:
[https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures](url)

**Guide to Download a File from GitHub** :point_down:
[https://www.wikihow.com/Download-a-File-from-GitHub](url)

I Hope This Helps :star:

**Comment by alokVerma749** [comment]
[Lectures](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures)
you will find all the notes in their respective folder 
> If you want to download the notes you can 
* clone the whole repo locally in your system 
*  you can click on download option of the notes
![image](https://user-images.githubusercontent.com/87599400/231705945-7ad37348-2f6b-484a-a572-5b2e31e72cf9.png)

**Comment by samuddhan-sttl** [comment]
Lectures -> AnyTopic -> pdf-for-that-topic -> download

If you are still confused you can refer to this - [https://ior.ad/97WB?iframeHash=viewsteps](url)
