### ISSUE TITLE
error rendring of notes

### ISSUE THREAD

**Issue by VaishnavVerma** [kunal-kushwaha/DSA-Bootcamp-Java#1064]
OOP notes is not loading and most of the notes are not opining.

**Comment by Techapurva** [comment]
same problem with me

**Comment by Krushna-Nanda** [comment]
> same problem with me

same problem here , but do you guys find any solution

**Comment by Manndar** [comment]
Same problem , please resolve this issue ..

**Comment by Vishal-Parasram** [comment]
Ya same issue.

**Comment by rishiraj88** [comment]
Opening well for me. In Firefox itself.

**Comment by prakash-santra** [comment]
I was facing the same Problem, but u guyz can Clone it maybe it will help you...

`git clone https://github.com/kunal-kushwaha/DSA-Bootcamp-Java.git`

**Comment by rishiraj88** [comment]
Thanks, @prakash-santra , for your suggestion to our loveable community.

**Comment by manoj-shetty** [comment]
> OOP notes is not loading and most of the notes are not opining.

Go to Control Panel > Network and Internet > Network and Sharing Center > Change Adapter Settings > (Right click on your network adapter) > properties > (double click on "Internet Protocol Version 4 (TCP/IPv4) " .
Click on Use following DNS server addresses and set preferred dns server to 8.8.8.8 and alternative to 8.8.4.4 and save it.
![image](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/assets/70282405/55f629a8-cdc6-4f6e-8593-cba60b7ed93c)

**Comment by Sahilkumar19** [comment]
> OOP notes is not loading and most of the notes are not opining.

#1146
