### ISSUE TITLE
Course releated

### ISSUE THREAD

**Issue by rishu6263** [kunal-kushwaha/DSA-Bootcamp-Java#1084]
please upload videos in consistent mode after 1 video of binary tree uploaded we are waiting for upcoming videos.

**Comment by GARY121github** [comment]
Bro don't get too much dependent on Kunal.
If you have come this far you can understand many things independently.

**Comment by rishu6263** [comment]
You are right bro. Same thing i heard today from Kunal bhaiya in a podcast he had with piyush garg.
