### ISSUE TITLE
Unable to download notes in the Lectutres section 

### ISSUE THREAD

**Issue by rishikeshkumar08** [kunal-kushwaha/DSA-Bootcamp-Java#1174]
not able to access any notes in the lectures please help regarding it.
-This is what is comes always(please see the attached screenshot.

![Screenshot (888)](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/assets/64651343/27cd46f5-2e88-46a1-83d0-20e5f1bd2e31)

**Comment by Vishwas2** [comment]
@rishikeshkumar08 clone the repo to your local system.

**Comment by Sahilkumar19** [comment]
> not able to access any notes in the lectures please help regarding it. -This is what is comes always(please see the attached screenshot.
> 
> ![Screenshot (888)](https://user-images.githubusercontent.com/64651343/271770755-27cd46f5-2e88-46a1-83d0-20e5f1bd2e31.png)

1. On the top you can see few options which are like codes , issues , pull request and all , Click on code
2. Now again you will see a green code option , just click on it and download the compressed zip file
3. now it will be downloaded to you pc
