### ISSUE TITLE
Out of index exception in infiniteArray.java 

### ISSUE THREAD

**Issue by Suvradippaul** [kunal-kushwaha/DSA-Bootcamp-Java#131]
### In [InfiniteArray.java](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java), in [line number 21](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/da08c80e694f5ee85ba2d37648cd5da77056582c/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java#L21), 'end' achieves such value which the array doesn't really have.

Eg - lets say our array has length of **11** and our target is in the **second half of the array**.

At starting,
start = 0
end = 1

After 1st execution of while loop, 
start = 2, end = 5

After 2nd execution of while loop, 
start = 6, end = **13**

Now at this line,
``` 
while (target > arr[end])
```
arr[end] means arr[13] which is not in the array.
And it raises an 'Index 13 out of bounds for length 11' exception.

Hope I am able to tell the issue in correct manner.

**Comment by RAMESSESII2** [comment]
Hey @Suvradippaul, your query is genuine. Theoretically, it's an infinite array, so an array index out of bound shouldn't be a question.
Although since we're hardcoding the array in the implementation, you can put a simple check condition after line 21->
**end = min(end, arr.length()-1);**
and that would suffice.

**Comment by avanish460** [comment]
hey, @Suvradippaul I solved your problem. you can see in pull request

**Comment by Suvradippaul** [comment]
Thank you both of you for clarification..
