### ISSUE TITLE
Adding Assignments shortcut in README.md

### ISSUE THREAD

**Issue by maheshvpawar** [kunal-kushwaha/DSA-Bootcamp-Java#140]
![image](https://user-images.githubusercontent.com/32674489/130390894-ab2e29c2-0311-458f-bea9-e6831ce7879d.png)
Like these links, there should have assignments link.

**Comment by ayushsom1** [comment]
Does the link to the assignment files in the repository suffice?

**Comment by ayushsom1** [comment]
Hello sir I would like to know if the work I have done on this issue is sufficient or is there anything else I should do.

**Comment by kunal-kushwaha** [comment]
done
