### ISSUE TITLE
[Request for an app] Requirements for community classroom app.

### ISSUE THREAD

**Issue by thisisamank** [kunal-kushwaha/DSA-Bootcamp-Java#151]
# Community Classroom app

## Goal

I went through the issues on DSA repository of community classroom and found some common ones, so planning to build a mobile app solving those issues. Please go through it and comment down what more requirements do you have.

### User app

1. Syllabus tracker:
   - syllabus tracker for all courses. As in when more courses will be added, the app should have it all.
   - Set up reminder to study.
   - not sure if authentication is needed in this app, if auth is required then probably we can go ahead with firestore to store user's progress. Otherwise we can use a simple local DB to store this.
2. All resources of each course at one place
   - video link, notes link etc 
3. notes sharing (needs approval as app might get spammed and loose quality)
4. Dark mode

We need approval for these two as this is already on discord so not sure if it's needed on app.

- announcement section (needs approval)

- opportunities  (needs approval)

### Admin app

This app will be used internally by of comm. classroom admins to post content on user app. It will have authentication and It will have features to crud new course, syllabus etc etc.

Need more input from your side, so please comment.

## Tech Stack

For backend we can use nodejs to make an API with all these requirements. We can have a separate admin panel kind of app/ web app for people who will post stuff on this app, so that can be either be on react or flutter.

For frontend of mobile app, we can use flutter.

## Architecture

I have not thought of architecture of this app as requirements may vary. But most probably it will either be BLoC patten or MVVM pattern depending on complexity of app.

**Comment by Gauravkhetwal** [comment]
hy i would like to work on this. I am completely new to it. But want to contribute in the community.

**Comment by piyush362** [comment]
Hey, I would also like to work in this. I am newbie here. But wants to contribute in the community.

**Comment by piyush362** [comment]
[ Feature request ] Want a bot that remind me gradually that hey " Piyush" you've to revise this topic that you cover last week.
So that we don't forget the things that we learns few week ago.

**Comment by kunal-kushwaha** [comment]
hey @thisisamank, please open similar issue here: https://github.com/commclassroom/mobileapp 
I have made you maintainer of repository. Please use github project board to create tasks and create issues for each task. Let me know who else will be working on this with you, I'll invite them to be maintainer too. for starters you can have a basic app ready.
