### ISSUE TITLE
Adding solutions to the assignments

### ISSUE THREAD

**Issue by 2024-SANDHYA** [kunal-kushwaha/DSA-Bootcamp-Java#152]
I would like to add the solutions to all the assignments, so people can refer them in case they get stuck somewhere in between.

**Comment by rhythmbhandari444** [comment]
It would be really helpfull

**Comment by dipankar-cmd** [comment]
Hey, I have a repository for the solutions of the assignments. It's a new repo and has like 8/9 solutions just the basic ones. I will upload other ones by the time. 

Link to the repo: [https://github.com/dipankar-cmd/Commclassroom-DR](url)

ps: You should make your repo like that and add assignments and notes to it. That's not necessary but still, it helps.

**Comment by kunal-kushwaha** [comment]
I'll start a repo for this soon and make announcement

**Comment by kapil5849** [comment]
I am new here. so, anyone can tell me how to submit solution.
if anyone free, please help me...

**Comment by hardikc** [comment]
Hey kunal can you please put all the solutions for your given assignment it would be a great help.

**Comment by CdrRjt** [comment]
can anyone  please provide with the solution of time complexity's assignment.

**Comment by adibaanwar** [comment]
Please kunal provide with the solutions of your assignment
