### ISSUE TITLE
Question is not clear

### ISSUE THREAD

**Issue by Deek9399** [kunal-kushwaha/DSA-Bootcamp-Java#160]
Question number 26 under Intermediate java program of Conditionals-loops assignment is little unclear to me.

Kunal is allowed to go out with his friends only on the even days of a given month. Write a program to check if he can go out in the month of August.

Does it mean Kunal is allowed to go out only in the months with even number of days?

**Comment by kunal-kushwaha** [comment]
please ask in discord
