### ISSUE TITLE
assignments Solution

### ISSUE THREAD

**Issue by anaskhan28** [kunal-kushwaha/DSA-Bootcamp-Java#168]
Some people cannot solve all questions and they google if they didn't find it most skip the question if we provide a folder of assignment solutions where people can put their solutions to check if write or not. Add them in it for future reference.

**Comment by thatbeautifuldream** [comment]
It's highly recommend to brainstorm over the questions, and get close to a working solution. At least if you follow the course holistically from the start you'll definatly be able to come up with either a brute force or a solution intuitively on pen and paper. I maintain my solutions maybe some are rather unoptimised for now, will keep on optimising as I learn myself. I maintain a repository for my solutions to the assignment here : 
# [Java DSA Bootcamp Assignment Solutions](https://github.com/thatbeautifuldream/java-dsa-bootcamp)

**Comment by geeky01adarsh** [comment]
You can find the solutions in Discuss section of every question. Btw, I am also maintaining 2 repos for solutions.
[Solutions of leetcode problems in C++](https://github.com/geeky01adarsh/DSA-Interview-Questions)
[Solution of assignments in JAVA](https://github.com/rishabhrathore055/DSA_in_java)
