### ISSUE TITLE
assignment solutions

### ISSUE THREAD

**Issue by subhiarjaria18** [kunal-kushwaha/DSA-Bootcamp-Java#169]
there need to be an assignment solution folder for it will give clarity of the answers.

**Comment by Kartik125** [comment]
this type of spoonfeeding will not be allowed you can find the solutions on your own.

**Comment by Kartik125** [comment]
@subhiarjaria18 at least try everything, What will you do if Kunal will do everything?

**Comment by Shivshankar158** [comment]
Unsubscribe me from this thread

**Comment by chetan-2002** [comment]
Hey  @subhiarjaria18, if you have any doubts regarding any question you can ask your question on the discord server.Cheers!

**Comment by AAYUSH-GUPTA-coder** [comment]
Hey @subhiarjaria18, if you have any doubt or face any problem you can also go to Discuss section of Leetcode. It will be very beneficial apart from that Community Classroom discord server is always there to help you. Try to challenge yourself. Cheers!

**Comment by subhiarjaria18** [comment]
> this type of spoonfeeding will not be allowed you can find the solutions on your own.

Haven't asked for spoon feeding don't take it into different sense..just asked for some sort of discussion forum where everybody discusses the approach of the solution to the problems... haven't mentioned that I want a solution to the questions by his end.

**Comment by thatbeautifuldream** [comment]
> problems

Saw the same type of issue else, where.

It's highly recommend to brainstorm over the questions, and get close to a working solution. At least if you follow the course holistically from the start you'll definatly be able to come up with either a brute force or a solution intuitively on pen and paper. I maintain my solutions maybe some are rather unoptimised for now, will keep on optimising as I learn myself. I maintain a repository for my solutions to the assignment here : 
## [Visit repository here](https://github.com/thatbeautifuldream/java-dsa-bootcamp)

Also started maintaining a blog for the same.
## [Visit blog here](https://thatbeautifuldream.github.io/java-dsa-bootcamp/)

I'd recommend you do the same for yourself and depend less on others. Also it's fun to maintain a blog post and all, helps you with the writing skills and all.

**Comment by subhiarjaria18** [comment]
Thanks

**Comment by thatbeautifuldream** [comment]
Close the issue if you got what you wanted.
