### ISSUE TITLE
bootcamp

### ISSUE THREAD

**Issue by akashqumar** [kunal-kushwaha/DSA-Bootcamp-Java#170]

**Comment by geeky01adarsh** [comment]
@akashqumar please don't spam here. Consider opening an issue only when you have a genuine doubt or suggestion or you know any mistake/bug.
Thank You!

**Comment by Kasera-Manish** [comment]
What's the issue @akashqumar ??

**Comment by kaiwalyakoparkar** [comment]
@kunal-kushwaha kindly close this issue :slightly_smiling_face:

**Comment by biradar73383** [comment]
suraj73383biradar@gmail.com im getting lots of emails please fix it

**Comment by biradar73383** [comment]
Im getting lots of emails
