### ISSUE TITLE
TwoSum before 3Sum

### ISSUE THREAD

**Issue by RakeshPotnuru** [kunal-kushwaha/DSA-Bootcamp-Java#171]
It would be better to add leetcode's [TwoSum](https://leetcode.com/problems/two-sum/) problem before 3Sum in [sorting assignment](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/assignments/7-sorting.md) problems for better understanding.

**Comment by PurneswarPrasad** [comment]
Good suggestion, there people can learn about 2 pointer method.

**Comment by Arnav-Barman** [comment]
The TwoSum problem is already mentioned in the array assignments.

**Comment by Arnav-Barman** [comment]
@RakeshPotnuru  
I find that the TwoSum question you've mentioned is the exact same question as the [21st question ](https://leetcode.com/problems/two-sum/)in the [arrays easy assignment ](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/assignments/5-arrays.md). Please have a look once. Though I think the question you are talking about is the [TwoSum II](https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/)

**Comment by RakeshPotnuru** [comment]
@Arnav-Barman 
Oh! Yes, but it would be better if it was in the sorting section. Anyways I am closing the issue now.
