### ISSUE TITLE
4 sum question page is showing not found error.

### ISSUE THREAD

**Issue by saurav935** [kunal-kushwaha/DSA-Bootcamp-Java#195]

**Comment by VishwaGauravIn** [comment]
Solved, Check now.

**Comment by VishwaGauravIn** [comment]
Solved, I think it will get updated shortly. Btw here is the link :- https://leetcode.com/problems/4sum/description/

**Comment by saurav935** [comment]
Hey, thanks for the link, but the link mentioned in the assignment page is still not working.

**Comment by VishwaGauravIn** [comment]
> Hey, thanks for the link, but the link mentioned in the assignment page is still not working.

You're Welcome ,
I have created a pull request, it will be approved soon.

**Comment by saurav935** [comment]
👍
