### ISSUE TITLE
Time and Space complexity priority

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kunal-kushwaha/DSA-Bootcamp-Java#2]
Hey, The syllabus is pretty neat but I had one suggestion. Can we shift `Time and Space complexity` lectures before `Array` lectures. As in array, we have sorting techniques. It would be good if we are taught `Complexities` beforehand so that it gets more clearer. What do you think?

**Comment by kunal-kushwaha** [comment]
Nope, the order is fine. Trust me.

**Comment by kaiwalyakoparkar** [comment]
No problem @kunal-kushwaha I trust you :+1: :heart:
