### ISSUE TITLE
Make Folder for all Assignment Solution 

### ISSUE THREAD

**Issue by abhiyanshusahu** [kunal-kushwaha/DSA-Bootcamp-Java#214]
Please make a collection of all assignment solution for reference.if any one have problem they can see and solve them.

**Comment by Gurdeep475** [comment]
Please put video solutions as well, if available.

**Comment by jaybamroliya** [comment]
> Please put video solutions as well, if available.

LeapYear Program
public class LeapYear {
    public static void main(String[] args) {

        int year=2016;
        if ((year%400==0) || (year%4==0 && year%100 !=0)){
            System.out.println("is a leapyear");
        }
        else {
            System.out.println("is not a leapyear");
        }


    }
}

**Comment by VishwaGauravIn** [comment]
I tried to create it , I also created a Pull Request but it was closed so I think they don't wan't to create solution folder as of now.

**Comment by kunal-kushwaha** [comment]
Why do you need assignment solutions when literally every question is on LeetCode and leetcode has solutions to all in the discussion tab?

**Comment by VishwaGauravIn** [comment]
True , I think some viewers are new to leetcode and that is why they are are unable to find solutions.

**Comment by jaybamroliya** [comment]
Sorry bro I delete the message my intension is only help but now I delete
the msg solution 🙏
