### ISSUE TITLE
Update "lectures" folder

### ISSUE THREAD

**Issue by ssk090** [kunal-kushwaha/DSA-Bootcamp-Java#247]
Rename files from '1' to '01' like that so it appears in correct order inside the 'lectures' folder.

**Comment by Subhadiptech** [comment]
I think its not needed coz people can track it based on number labels

**Comment by VishwaGauravIn** [comment]
@kunal-kushwaha Please do this if you want to , because 9 pull requests will be created if I try to do it 😅

**Comment by darthwithap** [comment]
++

**Comment by kunal-kushwaha** [comment]
okay i will
