### ISSUE TITLE
Advanced concepts apart from interviews

### ISSUE THREAD

**Issue by kunal-kushwaha** [kunal-kushwaha/DSA-Bootcamp-Java#274]
Check https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/SYLLABUS.md for progress.

**Comment by moshema10** [comment]
> Check https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/SYLLABUS.md for progress.

The link is not working. Can you please paste the syllabus progress tracker again? It would be helpful I was following to topic by topic to solve LC
