### ISSUE TITLE
JAVA throws a Array Index Out Of Bounds Exception - Infinite Array

### ISSUE THREAD

**Issue by soumyajoydas01** [kunal-kushwaha/DSA-Bootcamp-Java#277]
lectures/10-binary search/code/src/com/kunal/InfiniteArray.java
[Infinite Array](https://www.geeksforgeeks.org/find-position-element-sorted-array-infinite-numbers/)
If the target element is larger than the last element of the array then java throws an Array Index Out of Bounds Exception.
Example: 
int[ ] arr = {5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 75, 80}
target = 85;

OUTPUT:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 29 out of bounds for length 14
	at binarySearchQuestions.InfiniteArray.ans(InfiniteArray.java:22)
	at binarySearchQuestions.InfiniteArray.main(InfiniteArray.java:10)

**Comment by kunal-kushwaha** [comment]
please watch the video again. its Infinite Array then ignore this exception.

**Comment by Userismesuraj** [comment]
You can check the **closed issue #131**

**Comment by soumyajoydas01** [comment]
Okay got the point. Thank you both of you for the clarification.
