### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Vedantpr0** [kunal-kushwaha/DSA-Bootcamp-Java#297]
Kunal bhaiya can we get guide like Competitive Programming & System Design Resources for full stack web development please 🥺

**Comment by VishwaGauravIn** [comment]
He said, He may create if he get time and please create issue only related to this course/repository. Don't use it as DM. You can join Discord server or follow Kunal on Twitter for asking these stuffs. Hope you understand .
 # <img src="https://twemoji.twitter.com/content/dam/twemoji-twitter/Twitter_Social_Icon_Circle_Color.png.twimg.1920.png" width="28px">[ Kunal's Twitter](https://twitter.com/kunalstwt)
