### ISSUE TITLE
Find Pivot with Duplicates | Rotated Sorted Array | Binary Search

### ISSUE THREAD

**Issue by nvshah** [kunal-kushwaha/DSA-Bootcamp-Java#333]
### Issue

 `findPivotWithDuplicates(int[] arr)` is breaking in 1 case : 

### Explanation 

_Test Cases_ -> (Non-rotated array with odd length)

eg : 

1. [1, 2, 3]
2. [1, 2, 3, 4, 5]

> Error : ArrayIndexOutOfBoundException

**Comment by nvshah** [comment]
Attempted solution : 
https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/pull/334

**Comment by nvshah** [comment]
Also 1 more que I've @kunal-kushwaha 

```
static int findPivotWithDuplicates(int[] arr) {
    //.. rest loc

    // left side is sorted, so pivot should be in right
    else if(arr[start] < arr[mid] || (arr[start] == arr[mid] && arr[mid] > arr[end])) {
        start = mid + 1;
    }

    //.. rest loc
}
```

I cannot makeup with any scenario depicting use of above condition i.e 
> arr[start] < arr[mid] || (arr[start] == arr[mid] && arr[mid] > arr[end]) 

Instead can't we replace that condition with simple one i.e :- (_I've tried & till I didn't find any case breaking with it_)
> arr[start] < arr[mid]

<br>
Thanks 👍

**Comment by kunal-kushwaha** [comment]
let the students work it out
