### ISSUE TITLE
Some YouTube redirect links not working

### ISSUE THREAD

**Issue by danger-ahead** [kunal-kushwaha/DSA-Bootcamp-Java#408]
### Description of the issue:
In `SYLLABUS.md` under `Maths for DSA` section, `Complete Bitwise Operators` and `Range of numbers` redirects to an invalid URL in YouTube.

### Possible explanation:
This is caused due to the absence of Video ID in the URL.

**Comment by kunal-kushwaha** [comment]
Please make a PR for such small changes
