### ISSUE TITLE
Inconsistent ordering of assignment and lectures

### ISSUE THREAD

**Issue by wizzenalum** [kunal-kushwaha/DSA-Bootcamp-Java#445]
ordering of assignments should match the ordering of lectures 
### example
first assignment
```
01-flow-of-program.md
```
and first lecture is
```
01-Git
```
If the ordering of lecture matches the ordering of the assignments then it is little simpler for new users

**Comment by alokVerma749** [comment]
I made a PR regarding this issue,Please check it out

**Comment by shivammmmm** [comment]
> I made a PR regarding this issue,Please check it out

@alokVerma749 can you link that PR here for ref
