### ISSUE TITLE
Pdf not opening

### ISSUE THREAD

**Issue by shivamjaain** [kunal-kushwaha/DSA-Bootcamp-Java#499]
DSA-Bootcamp-Java/lectures/04-introduction to java/Introduction_to_Java_Notes.pdf

This gives, again and again, a loading error.

Like this
Sorry, something went wrong. Reload?

**Comment by ghulamrabbani883** [comment]
> 

Download the pdf on your local machine and then read, the only solutions I have found

**Comment by kabir0x17** [comment]
its working
