### ISSUE TITLE
Cant find DSA bootcamp notes

### ISSUE THREAD

**Issue by khadeshyam** [kunal-kushwaha/DSA-Bootcamp-Java#507]
Hey kunal I'm not able to find ur DSA boot camp NOTEs

**Comment by knight-95** [comment]
You can find the notes here https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures
Happy Learning !!

**Comment by khadeshyam** [comment]
> You can find the notes here https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures
> Happy Learning !!

Thanks but I want handwritten notes and   assignments of Java DSA

**Comment by coderdurgesh** [comment]
> > You can find the notes here https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures
> > Happy Learning !!
> 
> Thanks but I want handwritten notes and assignments of Java DSA

brother here itself you will find the written notes as well https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures

**Comment by alokVerma749** [comment]
> Hey kunal I'm not able to find ur DSA boot camp NOTEs

which chapter notes/assignment do you want. Please share so that we can help.

**Comment by Sidoryx** [comment]
> Hey kunal I'm not able to find ur DSA boot camp NOTEs

Bro, you can find the handwritten notes in the following way for the respective topics (Lets say you want notes for Switch cases) then follow this path:
 DSA-Bootcamp-Java->lectures->06-conditions-loops->switch->Handwritten notes switch cases.pdf
(https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures/06-conditions-loops/switch)
Similarly you can find the handwritten notes for the other rest of the topics 😄 Hope this helps.

**Comment by khadeshyam** [comment]
Tq

**Comment by mayankkuamr001** [comment]
I want notes of complexity lecture if anyone has please let me know

**Comment by alokVerma749** [comment]
HERE IT IS: https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/15-complexity/basics_of_time_complexity.png

**Comment by Deepa-chaurasiya01** [comment]
@mayankkuamr001 you can refer to this if you want it's in detail
https://github.com/Deepa-chaurasiya01/DSA-Bootcamp-Java/tree/main/lectures/15-complexity

**Comment by mayankkuamr001** [comment]
Thank you 😊 @alokVerma749 @Deepa-chaurasiya01

**Comment by adityajoshi304** [comment]
> > You can find the notes here https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/tree/main/lectures
> > Happy Learning !!
> 
> Thanks but I want handwritten notes and assignments of Java DSA

Hi, you can find the handwritten file by clicking on the lectures/<lecture name> folder and then on the pdf that is provided. These are the notes which Kunal makes while making the lectures. I hope I could help. Thanks!
<img width="1369" alt="Screenshot 2021-12-28 at 11 24 01 PM" src="https://user-images.githubusercontent.com/88195829/147593711-0ea357f3-3d6e-49f3-a611-39cf3a6e9892.png">
