### ISSUE TITLE
Error in wording in Git_GitHub_101 notes 

### ISSUE THREAD

**Issue by PurneswarPrasad** [kunal-kushwaha/DSA-Bootcamp-Java#51]
This notes has been uploaded by @kunal-bhadra
Do change the  line to "all the commits or changes **after** this ...."
![Screenshot (36)](https://user-images.githubusercontent.com/42652270/128461933-ea1d00f0-8f3a-4dd5-9105-83fc791af157.png)

**Comment by kunal-bhadra** [comment]
I see. @avanish460 has an open PR with a modified version of the file, please write to him as well

**Comment by ANURAG-PATHAK** [comment]
> This notes has been uploaded by @kunal-bhadra
> Do change the line to "all the commits or changes **after** this ...."
> ![Screenshot (36)](https://user-images.githubusercontent.com/42652270/128461933-ea1d00f0-8f3a-4dd5-9105-83fc791af157.png)

I have added a new pdf file after editing and replacing the old pdf file

**Comment by PurneswarPrasad** [comment]
Great! Closing this issue.
