### ISSUE TITLE
Infinite array might throw index out of bounds exception

### ISSUE THREAD

**Issue by lalithvaka** [kunal-kushwaha/DSA-Bootcamp-Java#591]
This might throw an index out of bounds exception if you search any  element close towards the end of the array as the following 

int [] arr = {1, 3, 5, 7, 8, 9, 10, 12, 15, 18};
int target = 12;

```
end = end + (end - start +1)*2; // doubling the box size **might be out of bounds.**
```
A brute force way is to add the following 
```
while (true) {
                try {
                    int test = arr[end];
                    break;
                } catch (Exception e) {
                    end = end - 1;
                }
}
```
https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java

**Comment by iyeraparna** [comment]
One way to prevent this is to add the extra check of end<len(nums) in the while loop condition keeping everything else the same

Something like:
while end < len(nums) and target>nums[end]:
        start = end + 1
        sizeofBox = sizeofBox*2
        end = end + sizeofBox

**Comment by kunal-kushwaha** [comment]
array is infinite so why care about out of bounds
