### ISSUE TITLE
Conditions and Loops Assignment pdf (repeated problem)corrections

### ISSUE THREAD

**Issue by thatbeautifuldream** [kunal-kushwaha/DSA-Bootcamp-Java#60]
-18. Volume of Prism
+18. Volume of Pyramid
![Screenshot 2021-08-07 at 11 51 33 PM](https://user-images.githubusercontent.com/28717686/128610330-03c61e2c-d3b7-4ed5-9771-bfaeb2ced890.png)

**Comment by avanish460** [comment]
okay don't worry I am going to remove it out and add a volume of the pyramid in that place

**Comment by avanish460** [comment]
hey @thatbeautifuldream I changed the prism to pyramid so now you can close this issue
