### ISSUE TITLE
Re-ordering of a medium difficulty problem in 06-Searching.md

### ISSUE THREAD

**Issue by MihirHundiwala** [kunal-kushwaha/DSA-Bootcamp-Java#600]
'Find Minimum in Rotated Sorted Array' in someway forms a base for the next question 'Search in Rotated Sorted Array'.

Current Order of Problems:
- [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/)
- [Search in Rotated Sorted Array II](https://leetcode.com/problems/search-in-rotated-sorted-array-ii/)
- [Find Minimum in Rotated Sorted Array](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/)

Expected Order:
- [Find Minimum in Rotated Sorted Array](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/)
- [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/)
- [Search in Rotated Sorted Array II](https://leetcode.com/problems/search-in-rotated-sorted-array-ii/)

Created a pull request for the same

**Comment by gaurangggaur** [comment]
I have made the required change. And created the pull request. Please let me know if it is accurate.

**Comment by gaurangggaur** [comment]
Sorry, I forgot to ask to get assigned first. Took the help of someone else (who was about to leave) to make my first contribution.

**Comment by AryanGodara** [comment]
I'll do this in 15 minutes.

**Comment by MihirHundiwala** [comment]
Pull Request #601 has already solved this issue
