### ISSUE TITLE
Syllabus tracker not available.

### ISSUE THREAD

**Issue by dhruv1503** [kunal-kushwaha/DSA-Bootcamp-Java#626]
Hi Kunal, I'm trying to access DSA syllabus, but I'm unable to find it. Have you deleted it or is there any error?

**Comment by bhagatpratik07** [comment]
Syllabus is available on website:  https://www.commclassroom.org/java

**Comment by alokVerma749** [comment]
I made a PR related to this issue.
PR is #629

**Comment by Sujansinh-thakor** [comment]
> Hi Kunal, I'm trying to access DSA syllabus, but I'm unable to find it. Have you deleted it or is there any error?

you find that in another branch : https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/kunal-kushwaha-patch-1/SYLLABUS.md

**Comment by alokVerma749** [comment]
PR #627 is related to this issue.
The syllabus tracker will be there as soon as this PR gets merged.
