### ISSUE TITLE
Can't calculate p whule solving T(n) = 7T(n/2) + n². Can you please provide solutions to the questions given for complexity problems.

### ISSUE THREAD

**Issue by devilkiller-ag** [kunal-kushwaha/DSA-Bootcamp-Java#668]

**Comment by wre9-tesh** [comment]
u can use discord channel for doubts .

for ur problem ....

we have,

a1= 7
b1 =1/2

we know ,
a1b1^p =1

=>7(1/2)^p =1
=>7 = 2^P

taking log

log 7 = p(log  2)

=> p = log 7 /log 2
=> p =2.8 (approx)

**Comment by kapilepatel** [comment]
@devilkiller-ag if the problem is solved, let's close the issue.

**Comment by devilkiller-ag** [comment]
Sure Sir. Thank you 😄
