### ISSUE TITLE
Some files not visible.

### ISSUE THREAD

**Issue by chetan-2002** [kunal-kushwaha/DSA-Bootcamp-Java#76]
Hey Kunal , When I am opening arrays.md and function.md file in the assignments folder, there is no content showing up inside it. If those files are still under work, please let us know, I will close this issue.

**Comment by Seranya1** [comment]
The questions have not been added yet...just the files have been created @chetan-2002

**Comment by RakeshPotnuru** [comment]
Kunal created a channel on discord called **assignment-forming-team**, so the DSA mentors will add questions. So, yes those are still under work. You can check [pull requests](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/pulls).

**Comment by chetan-2002** [comment]
Ok , i was not aware of that .So closing this issue now.
