### ISSUE TITLE
Assignment, 09-pattern, question no. 23.

### ISSUE THREAD

**Issue by Princek22** [kunal-kushwaha/DSA-Bootcamp-Java#764]
Can somebody help me to know whether the pattern in Q23 is depeded on intput (n) or is a fixed pattern that we have to print.

**Comment by NaveenGokavarapu19** [comment]
hii princek22 i think this question should be asked in discord instead of github.

**Comment by Princek22** [comment]
well, now that i think about it. you are 100% correct. thumps up.
