### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by Imraghu117** [kunal-kushwaha/DSA-Bootcamp-Java#769]
Can any one provide the solutions of these assignment questions ?

**Comment by PradeepRaoK** [comment]
You can find solutions in leetcode discussions.

**Comment by Sanketsingh77** [comment]
could you provide the link for that please. it would really help

**Comment by Mohammed-Saif0** [comment]
![IMG_20220920_083523](https://user-images.githubusercontent.com/99530963/191158415-521f30cf-5457-43c6-a2da-2dac9eec109b.jpg)

Just go into the discussion section of the question you will be able to see lot of people discussion the optimal solution.

**Comment by Mohammed-Saif0** [comment]
> Can any one provide the solutions of these assignment questions ?


Hey it will be great if you close this issue

**Comment by Imraghu117** [comment]
Thanks a lot , i appreciate this.
