### ISSUE TITLE
Arrays assignment

### ISSUE THREAD

**Issue by Kartik125** [kunal-kushwaha/DSA-Bootcamp-Java#77]
Array assignment is not visible.

**Comment by chetan-2002** [comment]
Hey @Kartik125 , I just opened a similar issue . It's better to have a single issue for a single problem.If you want you can close down this issue :)

**Comment by RakeshPotnuru** [comment]
@Kartik125 
This question has already been answered [here](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/issues/76)

**Comment by Kartik125** [comment]
okay thanks
