### ISSUE TITLE
Notes given show unable to render and not even able to download them please fix this.

### ISSUE THREAD

**Issue by Ayaz-Mohammed-Khan** [kunal-kushwaha/DSA-Bootcamp-Java#790]

**Comment by SensationalShubham** [comment]
yeah, please do something about it. I'm not able to access the notes.

**Comment by asdsyd** [comment]
> yeah, please do something about it. I'm not able to access the notes.

You can access the notes in the lectures folder of this repo.
![Screenshot 2022-10-11 at 10 42 10 AM](https://user-images.githubusercontent.com/77977076/195002499-75b612b1-0596-4eba-9b56-f8c1aaa3b969.png)

**Comment by asdsyd** [comment]
Notes are accessible and up for download. Please close this issue. Thanks.
