### ISSUE TITLE
bug in calculator code

### ISSUE THREAD

**Issue by vinay9354** [kunal-kushwaha/DSA-Bootcamp-Java#84]
i found a small bug in calculator code with a small change in ans output
(first do an arithmetic operation with any operator and then in next step give an invalid operator  the getting the output as invalid operation and the ans of before arithmetic operation i mean getting output both the operations again)
changed code:
package com.coffee;

import java.util.Scanner;

public class SimpleCalci {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int ans = 0;
        while (true) {
            System.out.println("enter an operator");
            char op = in.next().trim().charAt(0);
            if (op == '+' || op == '-' || op == '*' || op == '%' || op == '/') {
                System.out.println("enter two numbers");
                int num1 = in.nextInt();
                int num2 = in.nextInt();
                if (op == '+') {
                    ans = num1 + num2;
                }
                if (op == '-') {
                    ans = num1 - num2;
                }
                if (op == '*') {
                    ans = num1 * num2;
                }
                if (op == '%') {
                    ans = num1%num2;
                }
                if (op == '/') {
                    if (num2 != 0) {
                        ans = num1 / num2;
                    }
                    ans = num1 / num2;
                }
                System.out.println(ans);
            } else if (op == 'x' || op == 'X') {

                break;
            } else {
                System.out.println("invalid operation");
            }

        }

    }
}

**Comment by imminal35** [comment]
Hey @vinay9354 , few small observations:
1. Multiplication symbol is missing from two places in this code.
2. Description is not clear . Please elaborate why its marked as issue. (if possible)

**Comment by vinay9354** [comment]
> i found a small bug in calculator code with a small change in ans output
> (first do an arithmetic operation with any operator and then in next step give an invalid operator the getting the output as invalid operation and the ans of before arithmetic operation i mean getting output both the operations again)
> changed code:
> package com.coffee;
> 
> import java.util.Scanner;
> 
> public class SimpleCalci {
> public static void main(String[] args) {
> Scanner in = new Scanner(System.in);
> int ans = 0;
> while (true) {
> System.out.println("enter an operator");
> char op = in.next().trim().charAt(0);
> if (op == '+' || op == '-' || op == '_' || op == '%' || op == '/') { System.out.println("enter two numbers"); int num1 = in.nextInt(); int num2 = in.nextInt(); if (op == '+') { ans = num1 + num2; } if (op == '-') { ans = num1 - num2; } if (op == '_') {
> ans = num1 * num2;
> }
> if (op == '%') {
> ans = num1%num2;
> }
> if (op == '/') {
> if (num2 != 0) {
> ans = num1 / num2;
> }
> ans = num1 / num2;
> }
> System.out.println(ans);
> } else if (op == 'x' || op == 'X') {
> 
> ```
>             break;
>         } else {
>             System.out.println("invalid operation");
>         }
> 
>     }
> 
> 
> }
> ```
> 
> }
