### ISSUE TITLE
Unable to get access to the notes 

### ISSUE THREAD

**Issue by deepak-777** [kunal-kushwaha/DSA-Bootcamp-Java#847]
for the past 4~5 days,  Iam unable to get access to the notes 
it just says ""Unable to render rich display""
can you please fix it upp.

**Comment by Anik-Gautam** [comment]
> for the past 4~5 days, Iam unable to get access to the notes it just says ""Unable to render rich display"" can you please fix it upp.

please give access

**Comment by deepak-777** [comment]
> I was having the same problem. Download the entire repository, that way the notes get downloaded as well. Individual notes can't be downloaded somehow.


Thanks a lot.

**Comment by Shweta200126** [comment]
> > I was having the same problem. Download the entire repository, that way the notes get downloaded as well. Individual notes can't be downloaded somehow.
> 
> Thanks a lot.

You're welcome.
