### ISSUE TITLE
Handwritten notes

### ISSUE THREAD

**Issue by Himanshu-Udupa** [kunal-kushwaha/DSA-Bootcamp-Java#876]
All the hand written notes are not available. I am able to access only the codes present in repository. Can anyone help me out to sort my problem.

**Comment by deepak-777** [comment]
Hey, Himanshu even I was facing the same problem, thanks to [Shweta200126] who helped me out. 
Just download the entire repository, that way the notes get downloaded and you can access it directly on your PC.

you can download it by coming to the main page of the DSA-Bootcamp-Java repository then **click** the green "code" button on the top and select the "Download zip" option from the "code".That's it.

Hope it helps you.

**Comment by Himanshu-Udupa** [comment]
Thank you bro. I will try it as soon as  possible

**Comment by Himanshu-Udupa** [comment]
Thank you so much @deepak-777 for making time in addressing my issue. Your reply helped me to download the whole repository through which I could access all the notes.

**Comment by connectwithpankaj** [comment]
the hand written notes are not available. I am able to access only the codes present in repository. Can anyone help me out to sort my problem.

**Comment by Himanshu-Udupa** [comment]
I am able to access all the handwritten notes as I downloaded the whole DS
repository recently. I did so by clicking on "Download Zip" option given in
the green colour "Code" button present in the home screen of the
repository. Thanks to @deepak-777 who helped me to solve the problem.

**Comment by deepak-777** [comment]
> 
you're welcome, Himanshu.
Glad to help.
