### ISSUE TITLE
Error in code 

### ISSUE THREAD

**Issue by vagabon-09** [kunal-kushwaha/DSA-Bootcamp-Java#888]
# Binary Search
## InfiniteArray
In this code if I give target 100 then it is showing an error "IndexOutOfBound" please fix this error.

**Comment by kelvinparmar** [comment]
In which code?

**Comment by vagabon-09** [comment]
[Code Link](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/10-binary%20search/code/src/com/kunal/InfiniteArray.java)

**Comment by kelvinparmar** [comment]
![example](https://user-images.githubusercontent.com/94775043/210333654-b4d7a4a6-c5b6-4b72-b7bb-42401494cf8c.JPG)

**Comment by vagabon-09** [comment]
@deep1910 `thanks for resolving the issue`

**Comment by deep1910** [comment]
I am beginner in contributing can you pls let me know that why u closed the
issue rather than merging
just want to know how github works

**Comment by vagabon-09** [comment]
I am not the `owner `of that repository so I can't marge; If you are a beginner you can go through `YouTube `videos.
