### ISSUE TITLE
Commclassroom.org Website Not Working #909

### ISSUE THREAD

**Issue by anand7171** [kunal-kushwaha/DSA-Bootcamp-Java#938]
Hey Kunal sir, 
Please checkout your Website it is not opening. I m a new student and just starting your dsa series. Please solve it.

**Comment by alokVerma749** [comment]
Hey @anand7171 https://wemakedevs.org/ is the new running website 
Hope this helps.

**Comment by anand7171** [comment]
Thank you for this I appreciate your help
