### ISSUE TITLE
Order the assignments in a numbered way according to the order of the videos in the DSA Playlist.

### ISSUE THREAD

**Issue by TaherPatan** [kunal-kushwaha/DSA-Bootcamp-Java#99]
Please order the assignments in the order of the videos in the DSA playlist as when the number of videos increase in the playlist and the number of assignments increase this lack of order would cause issues and confusion while finding the assignments, a proper order and format would help in ease of access and understanding of the content in a better way.

**Comment by RAMESSESII2** [comment]
Github arranges files lexicographically. In that case, we can just rename the assignments adding numbers so that they can be arranged in the more facilitating way.

**Comment by imminal35** [comment]
I think, its a good idea. 
I have created one PR for this fix and added numbers as index. 
Hey @kunal-kushwaha.  if you think this should be followed , Please review this PR. 

PR # ---- added numbers as index #100

**Comment by RAMESSESII2** [comment]
@imminal35 LOL I should've told you I was already working on it.

**Comment by imminal35** [comment]
> @imminal35 LOL I should've told you I was already working on it.

Oops, Same work !!!

**Comment by kunal-kushwaha** [comment]
merged
