### ISSUE TITLE
PDF Unable to open

### ISSUE THREAD

**Issue by bisen-del** [kunal-kushwaha/DSA-Bootcamp-Java#996]

**Comment by alokVerma749** [comment]
which particular pdf, can you specify

**Comment by bisen-del** [comment]
Bubble sort pdf is not working

**Comment by bisen-del** [comment]
pdf of bubble sort is not working

**Comment by alokVerma749** [comment]
it is working fine
[pdf link](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/lectures/11-sorting/Bubble%20Sort.pdf)

**Comment by bisen-del** [comment]
I dont't know why but that link you sent  it is also not working

**Comment by alokVerma749** [comment]
[Bubble Sort.pdf](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/files/11183080/Bubble.Sort.pdf)
Hope this works🤞

**Comment by bisen-del** [comment]
Yeah it's working 👍
Thanks
